# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

container:
  image: circleci/node:latest-browsers
  options: '-u root'

jobs:
  - job: linux-lint
    steps:
      - script: npm install
      - script: npm run lint

  - job: linux-build
    steps:
      - script: npm install
      - script: npm run build
  - job: linux-test
    steps:
      - script: npm install
      - script: npm run test:all

  - job: Subsequent
    dependsOn:
      - InitialA
      - InitialB
    steps:
      - script: echo hello from subsequent
